### ISSUE TITLE
It does not work on ie?

### ISSUE THREAD

**Issue by fewiki** [NicolasRitouet/dpd-fileupload-demo#3]
Hi, the plugin does not work on ie9? Is it right?

**Comment by NicolasRitouet** [comment]
I don't know, I haven't tried.
Did somebody else tried?

**Comment by NicolasRitouet** [comment]
Well, actually, dpd-fileupload is mostly backend stuff, the browser shouldn't be a problem.
The client-side implementation that you do to upload the files may need to be tested with IE9.
This repo is just a quick demo of `dpd-fileupload` and probably doesn't work on IE9.
