### ISSUE TITLE
keep getting error messages when choosing image then trying to upload

### ISSUE THREAD

**Issue by mattlbrody** [NicolasRitouet/dpd-fileupload-demo#4]
I receive this image when I choose the image using the choose file button: Uncaught ReferenceError: setFiles is not defined

And this error when I click submit when trying to save it: Uncaught ReferenceError: uploadFiles is not defined 

This seems odd because everything else is working fine. I copied and pasted your files exactly into my program. Not sure how why it doesn't recognize those functions.

**Comment by NicolasRitouet** [comment]
Can you give me more details?
A stacktrace?
A screenshot?
A repo with your code maybe?
