### ISSUE TITLE
After install upload isn't in dashboard

### ISSUE THREAD

**Issue by michalmw** [NicolasRitouet/dpd-fileupload-demo#6]
Hello,
i use deployd in my project, and wanna install you plugin.

In terminal:
```
npm install dpd-fileupload --save
npm WARN engine dpd-fileupload@0.0.15: wanted: {"node":">= 0.11"} (current: {"node":"0.10.40","npm":"1.4.28"})
dpd-fileupload@0.0.15 ../node_modules/dpd-fileupload
├── mime@1.3.4
├── formidable@1.0.17
├── debug@2.2.0 (ms@0.7.1)
├── md5@2.0.0 (charenc@0.0.1, crypt@0.0.1, is-buffer@1.0.2)
└── lodash@3.10.1
```

And when start my serv.js script:
````
var deployd = require('deployd'),
        options = {port: 2406};
var dpd = deployd(options);
dpd.listen();

console.log('Server running at http://127.0.0.1:2404/');


````
I don;t have this funcion in my panel. Why?

**Comment by NicolasRitouet** [comment]
Do you already have a package.json file at the root of your project?

**Comment by tekinarslan** [comment]
Hi,
I install module and I dont see in my dashboard and I have package.json file my root folder of project(package.json has same location as node_modules and my app folder)

**Comment by NicolasRitouet** [comment]
In the dashboard, can you see the resource `file upload` when you click on the + icon?

**Comment by tekinarslan** [comment]
No, I cannot see it.

**Comment by NicolasRitouet** [comment]
can you share some code?
Since it seems to work for most of the users, let's try to figure out what's different with your setup.

**Comment by tekinarslan** [comment]
Hi Nicolas,
I solve my problem, problem is my project folder does not contain node_modules folder and your module not create this folder automatically. I create folder into project folder and your module command get deployd and your module. So ,it was runned.

**Comment by NicolasRitouet** [comment]
well, `npm` install takes care of creating the `node_modules` folder.
No module can and should create the `node_modules` folder.
Glad it was solved :+1:
